modLoader="javafml"
loaderVersion="[32,)"
license="MIT License - Copyright (c) 2019 Trident"
[[mods]]
modId="molecule"
version="${file.jarVersion}"
displayName="Molecule"
description='''
Molecule is the test mod used for the development of Trident Compound.
'''